### ISSUE TITLE
Installation with lubridate package on AIX7.2 failed due to mutex error

### ISSUE THREAD

**Issue by bergen288** [google/cctz#146] opened 2020-05-28 18:13 UTC
I am trying to install R packages (R base is 3.6.1) on AIX7.2 server with no internet access. My installation with lubridate package failed due to mutex error.  See my issue here: 
https://github.com/tidyverse/lubridate/issues/894

It is said the error is related with "cctz" and I am suggested to ask question here.  Can someone told me what direction should I take?

By the way, I had mutex error with RcppArmadillo/forecast packages as well.  They are installed successfully after "-DARMA_DONT_USE_CXX11_MUTEX" are appended in CXXFLAGS & CXX11FLAGS.  However, lubridate package still has mutex error as shown below.  You can see "-DARMA_DONT_USE_CXX11_MUTEX" at the end of g++ statements.

```r
* installing *source* package 'lubridate' ...
** package 'lubridate' successfully unpacked and MD5 sums checked
** using staged installation
** libs
        g++ -maix64 -std=gnu++11 -I"/opt/freeware/lib64/R/include" -DNDEBUG -I. -I./cctz/include/ -I./cctz/src/ -I"/software/R/site-library/Rcpp/include" -O2 -I/opt/freeware/include -I/usr/include -D_GETDELIM    -O2 -I/opt/freeware/include -I/usr/include -D_GETDELIM  -DARMA_DONT_USE_CXX11_MUTEX -c ./cctz/src/time_zone_fixed.cc -o ./cctz/src/time_zone_fixed.o
        g++ -maix64 -std=gnu++11 -I"/opt/freeware/lib64/R/include" -DNDEBUG -I. -I./cctz/include/ -I./cctz/src/ -I"/software/R/site-library/Rcpp/include" -O2 -I/opt/freeware/include -I/usr/include -D_GETDELIM    -O2 -I/opt/freeware/include -I/usr/include -D_GETDELIM  -DARMA_DONT_USE_CXX11_MUTEX -c ./cctz/src/time_zone_if.cc -o ./cctz/src/time_zone_if.o
        g++ -maix64 -std=gnu++11 -I"/opt/freeware/lib64/R/include" -DNDEBUG -I. -I./cctz/include/ -I./cctz/src/ -I"/software/R/site-library/Rcpp/include" -O2 -I/opt/freeware/include -I/usr/include -D_GETDELIM    -O2 -I/opt/freeware/include -I/usr/include -D_GETDELIM  -DARMA_DONT_USE_CXX11_MUTEX -c ./cctz/src/time_zone_impl.cc -o ./cctz/src/time_zone_impl.o
./cctz/src/time_zone_impl.cc:34:6: error: 'mutex' in namespace 'std' does not name a type
 std::mutex time_zone_mutex;
      ^~~~~
./cctz/src/time_zone_impl.cc:34:1: note: 'std::mutex' is defined in header '<mutex>'; did you forget to '#include <mutex>'?
./cctz/src/time_zone_impl.cc:23:1:
+#include <mutex>

./cctz/src/time_zone_impl.cc:34:1:
 std::mutex time_zone_mutex;
 ^~~
./cctz/src/time_zone_impl.cc: In static member function 'static bool cctz::time_zone::Impl::LoadTimeZone(const string&, cctz::time_zone*)':
./cctz/src/time_zone_impl.cc:55:26: error: 'mutex' is not a member of 'std'
     std::lock_guard<std::mutex> lock(time_zone_mutex);
                          ^~~~~
./cctz/src/time_zone_impl.cc:55:26: note: 'std::mutex' is defined in header '<mutex>'; did you forget to '#include <mutex>'?
./cctz/src/time_zone_impl.cc:55:26: error: 'mutex' is not a member of 'std'
./cctz/src/time_zone_impl.cc:55:26: note: 'std::mutex' is defined in header '<mutex>'; did you forget to '#include <mutex>'?
./cctz/src/time_zone_impl.cc:55:31: error: template argument 1 is invalid
     std::lock_guard<std::mutex> lock(time_zone_mutex);
                               ^
./cctz/src/time_zone_impl.cc:55:38: error: 'time_zone_mutex' was not declared in this scope
     std::lock_guard<std::mutex> lock(time_zone_mutex);
                                      ^~~~~~~~~~~~~~~
./cctz/src/time_zone_impl.cc:55:38: note: suggested alternative: 'time_zone'
     std::lock_guard<std::mutex> lock(time_zone_mutex);
                                      ^~~~~~~~~~~~~~~
                                      time_zone
./cctz/src/time_zone_impl.cc:66:24: error: 'mutex' is not a member of 'std'
   std::lock_guard<std::mutex> lock(time_zone_mutex);
                        ^~~~~
./cctz/src/time_zone_impl.cc:66:24: note: 'std::mutex' is defined in header '<mutex>'; did you forget to '#include <mutex>'?
./cctz/src/time_zone_impl.cc:66:24: error: 'mutex' is not a member of 'std'
./cctz/src/time_zone_impl.cc:66:24: note: 'std::mutex' is defined in header '<mutex>'; did you forget to '#include <mutex>'?
./cctz/src/time_zone_impl.cc:66:29: error: template argument 1 is invalid
   std::lock_guard<std::mutex> lock(time_zone_mutex);
                             ^
./cctz/src/time_zone_impl.cc:66:36: error: 'time_zone_mutex' was not declared in this scope
   std::lock_guard<std::mutex> lock(time_zone_mutex);
                                    ^~~~~~~~~~~~~~~
./cctz/src/time_zone_impl.cc:66:36: note: suggested alternative: 'time_zone'
   std::lock_guard<std::mutex> lock(time_zone_mutex);
                                    ^~~~~~~~~~~~~~~
                                    time_zone
make: 1254-004 The error code from the last command is 1.

Stop.
ERROR: compilation failed for package 'lubridate'
* removing '/software/R/site-library/lubridate'
```

**Comment by devjgm** [comment] 2020-05-28 18:43
Thanks for the bug report. What version of g++? `g++ --version`

**Comment by bergen288** [comment] 2020-05-28 18:46
```r
g++ (GCC) 8.3.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by devbww** [comment] 2020-05-28 18:52
I don't know where `-DARMA_DONT_USE_CXX11_MUTEX` originated, but it looks suspicious.

**Comment by devjgm** [comment] 2020-05-28 18:54
From about 11 days ago: http://dirk.eddelbuettel.com/blog/2020/05/17/

```
...
added ARMA_DONT_USE_CXX11_MUTEX confguration option to disable use of std::mutex
...
```
:shrug:

**Comment by bergen288** [comment] 2020-05-28 19:00
As I mentioned, my installation of RcppArmadillo/forecast packages failed with mutex error at first. ``` DARMA_DONT_USE_CXX11_MUTEX ``` option helped me to install them successfully.  Since the failure of lubridate package is also related with mutex error, I guess there is nothing to lose to try it.

**Comment by bergen288** [comment] 2020-05-29 20:14
Is there any clue or direction to fix the issue?

Thanks.

**Comment by devbww** [comment] 2020-05-29 20:43
Hi bergen288.  I don't think we have anything for you.  As I mentioned, CCTZ uses `std::mutex`, so you're going to have trouble if you disable it.  My only suggestion would be to investigate why really you need `ARMA_DONT_USE_CXX11_MUTEX` in the first place.

**Comment by vspinu** [comment] 2020-05-31 20:01
I think @bergen288 issue is the same without including DARMA_DONT_USE_CXX11_MUTEX. Could it be that AIX7.2  is removing mutex by design?

**Comment by kadler** [comment] 2020-11-11 01:20
AIX GCC has a split pthread/non-pthread ABI. In order to use `std::mutex`, you need to add `-pthread` to CFLAGS and LDFLAGS.

**Comment by devbww** [comment] 2020-11-11 21:43
Thanks Kevin.  And with that advice, I believe we can close this.

**Closed by devbww** 2020-11-11 21:43 UTC
